version: "3"

services:

  iconator-core:
    restart: always
    image: iconator/core:latest
    container_name: iconator-core
    hostname: iconator-core
    networks:
      - iconator-network
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq-service
      - postgres-service
      - logstash-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NONCONTEXTUALCREATION=true
      - JPA_HIBERNATE_DDL_AUTO=create-drop
      - JPA_GENERATE_DDL_ENABLED=true
      - DATASOURCE_URL=jdbc:postgresql://postgres-service/testuser
      - DATASOURCE_USERNAME=testuser
      - DATASOURCE_PASSWORD=testpass
      - ICONATOR_BACKEND_URL=http://localhost:8081
      - ICONATOR_FRONTEND_URL=http://localhost:8080
      - ICONATOR_FRONTEND_WALLET_PATH=/confirm/
      - ICONATOR_CORE_KEYPAIRS_GEN_OUTPUT_FILE=/ICOnator/keypairs.keys
      - ICONATOR_CORE_KEYPAIRS_GEN_AMOUNT=30
      - ICONATOR_CORS_URLS=*
      - ICONATOR_AUTH_ACTUATOR_USER=user
      - ICONATOR_AUTH_ACTUATOR_PASSWORD=password
      - CORE_RECAPTCHA_ENABLED=${CORE_RECAPTCHA_ENABLED}
      - CORE_RECAPTCHA_SECRET_KEY=${CORE_RECAPTCHA_SECRET_KEY}
      - CORE_COUNTRY_FILTER_ENABLED=false
      - CORE_COUNTRY_FILTER_DISALLOW=US,NZ,UK,CN
      - LOGSTASH_ADDRESS=logstash-service:5000
      - AMQP_URL=amqp://guest:guest@rabbitmq-service/vhost1?exchangeName=iconator_entry_exchange&exchangeType=topic&durable=true&autoDelete=false
      - BITCOIN_NETWORK=testnet
    healthcheck:
      test: ["CMD-SHELL", "curl http://iconator-core:8081/actuator"]
      interval: 30s
      timeout: 10s
      retries: 3

  iconator-monitor:
    restart: always
    image: iconator/monitor:latest
    container_name: iconator-monitor
    hostname: iconator-monitor
    networks:
      - iconator-network
    depends_on:
      - iconator-core
      - postgres-service
      - rabbitmq-service
      - logstash-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NONCONTEXTUALCREATION=true
      - JPA_HIBERNATE_DDL_AUTO=none
      - JPA_GENERATE_DDL_ENABLED=false
      - DATASOURCE_URL=jdbc:postgresql://postgres-service/testuser
      - DATASOURCE_USERNAME=testuser
      - DATASOURCE_PASSWORD=testpass
      - MONITOR_BITCOIN_NODE_ENABLED=true
      - MONITOR_ETHEREUM_NODE_ENABLED=true
      - MONITOR_ETHEREUM_NODE_START_BLOCK=8609646
      - MONITOR_ETHEREUM_NODE_URL=${MONITOR_ETHEREUM_NODE_URL}
      - MONITOR_BITCOIN_CONFIRMATION_BLOCKDEPTH=6
      - MONITOR_ETHEREUM_CONFIRMATION_BLOCKDEPTH=6
      - MONITOR_TOTAL_TOKEN_AMOUNT=100000000
      - MONITOR_FIAT_BASE_PER_TOKEN=0.1
      - MONITOR_ATOMIC_TOKEN_UNIT_FACTOR=18
      - MONITOR_TRANSACTION_PROCESSING_TIME=60000
      - MONITOR_FIAT_BASE_PAYMENT_MIN=10
      - ICONATOR_AUTH_ACTUATOR_USER=user
      - ICONATOR_AUTH_ACTUATOR_PASSWORD=password
      - LOGSTASH_ADDRESS=logstash-service:5000
      - AMQP_URL=amqp://guest:guest@rabbitmq-service/vhost1?exchangeName=iconator_entry_exchange&exchangeType=topic&durable=true&autoDelete=false
      - BITCOIN_NETWORK=testnet
    healthcheck:
      test: ["CMD-SHELL", "curl http://iconator-monitor:8082/actuator"]
      interval: 30s
      timeout: 10s
      retries: 3

  iconator-rates:
    restart: always
    image: iconator/rates:latest
    container_name: iconator-rates
    hostname: iconator-rates
    networks:
      - iconator-network
    ports:
      - "8083:8083"
    depends_on:
      - iconator-core
      - postgres-service
      - rabbitmq-service
      - logstash-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NONCONTEXTUALCREATION=true
      - JPA_HIBERNATE_DDL_AUTO=none
      - JPA_GENERATE_DDL_ENABLED=false
      - DATASOURCE_URL=jdbc:postgresql://postgres-service/testuser
      - DATASOURCE_USERNAME=testuser
      - DATASOURCE_PASSWORD=testpass
      - RATES_FETCH_PERIODIC_ENABLED=true
      - RATES_FETCH_PERIODIC_INTERVAL=60000
      - RATES_RETRY_ATTEMPTS_MAX=3
      - RATES_RETRY_BETWEEN_ATTEMPTS_MIN=100
      - RATES_RETRY_BETWEEN_ATTEMPTS_MAX=1000
      - RATES_USER_AGENT=ICOnator-Rates-Client
      - RATES_CURRENCIES_FIAT_BASE=USD
      - RATES_CURRENCIES_CRYPTO_ENABLED=BTC,ETH
      - RATES_EXCHANGES_ENABLED=KRAKEN,BITFINEX,BITSTAMP,COINMARKETCAP,GDAX
      - RATES_OUTLIERS_STDDEV_LOWER_BOUND=2
      - RATES_OUTLIERS_STDDEV_UPPER_BOUND=2
      - RATES_FETCH_HISTORICAL_ENABLED=true
      - RATES_FETCH_RANGE_BETWEEN_THRESHOLD_MIN=7200000
      - RATES_FETCH_RANGE_BETWEEN_THRESHOLD_MAX=7200000
      - RATES_BLOCKNR_FALLBACK_API_ENABLED=true
      - RATES_BLOCKNR_FALLBACK_API_BITCOIN_OLDER_THAN=7200000
      - RATES_BLOCKNR_FALLBACK_API_ETHEREUM_OLDER_THAN=1800000
      - ICONATOR_CORS_URLS=*
      - ICONATOR_AUTH_ACTUATOR_USER=user
      - ICONATOR_AUTH_ACTUATOR_PASSWORD=password
      - LOGSTASH_ADDRESS=logstash-service:5000
      - AMQP_URL=amqp://guest:guest@rabbitmq-service/vhost1?exchangeName=iconator_entry_exchange&exchangeType=topic&durable=true&autoDelete=false
      - BITCOIN_NETWORK=testnet
    healthcheck:
      test: ["CMD-SHELL", "curl http://iconator-rates:8083/actuator"]
      interval: 30s
      timeout: 10s
      retries: 3

  iconator-email:
    restart: always
    image: iconator/email:latest
    container_name: iconator-email
    hostname: iconator-email
    networks:
      - iconator-network
    depends_on:
      - postgres-service
      - rabbitmq-service
      - logstash-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EMAIL_LOGO_URL=https://iconator.io/images/iconator-logo.png
      - EMAIL_LOGO_CONTENT_TYPE=image/png
      - EMAIL_LOGO_HEIGHT=70
      - EMAIL_LOGO_WIDTH=360
      - EMAIL_FOOTER_ENTITY_NAME=ICOnator Project
      - EMAIL_FOOTER_YEAR=2017
      - EMAIL_CONFIRMATION_SUBJECT=ICOnator.io - Demo Token Sale
      - EMAIL_SUMMARY_SUBJECT=ICOnator.io - Summary of your Demo Investment Details
      - EMAIL_TRANSACTION_RECEIVED_SUBJECT=ICOnator.io - Transaction Detected
      - EMAIL_TOKENS_ALLOCATED_SUBJECT=ICOnator.io - Your Tokens
      - EMAIL_TOKEN_SYMBOL=ICONATOR
      - EMAIL_TOKEN_SALE_NAME=ICOnator token sale
      - EMAIL_ENABLED=true
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PROTOCOL=smtp
      - EMAIL_PORT=587
      - EMAIL_AUTH_ENABLED=true
      - EMAIL_START_TLS_ENABLED=true
      - EMAIL_DEBUG_ENABLED=false
      - EMAIL_TRUST=*
      - EMAIL_USERNAME=${GMAIL_USER}
      - EMAIL_PASSWORD=${GMAIL_PASSWORD}
      - EMAIL_ADMIN_ADDRESS=info@ICOnator.io
      - EMAIL_BCC_CONFIRMATION_ENABLED=false
      - EMAIL_BCC_SUMMARY_ENABLED=false
      - EMAIL_SEND_FROM_ADDRESS=${EMAIL_SEND_FROM_ADDRESS}
      - ICONATOR_AUTH_ACTUATOR_USER=user
      - ICONATOR_AUTH_ACTUATOR_PASSWORD=password
      - LOGSTASH_ADDRESS=logstash-service:5000
      - AMQP_URL=amqp://guest:guest@rabbitmq-service/vhost1?exchangeName=iconator_entry_exchange&exchangeType=topic&durable=true&autoDelete=false
      - BITCOIN_NETWORK=testnet
    healthcheck:
      test: ["CMD-SHELL", "curl http://iconator-email:8084/actuator"]
      interval: 30s
      timeout: 10s
      retries: 3

  iconator-kyc:
    restart: always
    image: iconator/kyc:latest
    container_name: iconator-kyc
    hostname: iconator-kyc
    networks:
      - iconator-network
    ports:
      - "8085:8085"
    depends_on:
      - iconator-core
      - postgres-service
      - rabbitmq-service
      - logstash-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NONCONTEXTUALCREATION=true
      - JPA_HIBERNATE_DDL_AUTO=none
      - JPA_GENERATE_DDL_ENABLED=false
      - DATASOURCE_URL=jdbc:postgresql://postgres-service/testuser
      - DATASOURCE_USERNAME=testuser
      - DATASOURCE_PASSWORD=testpass
      - KYC_CLIENT_RETRY_ATTEMPTS_MAX=3
      - KYC_CLIENT_RETRY_BETWEEN_ATTEMPTS_MIN=100
      - KYC_CLIENT_RETRY_BETWEEN_ATTEMPTS_MAX=1000
      - ICONATOR_KYC_HOST=https://gateway.test.idnow.de
      - ICONATOR_KYC_COMPANY_ID=testId
      - ICONATOR_KYC_API_KEY=testKey
      - ICONATOR_AUTH_ACTUATOR_USER=user
      - ICONATOR_AUTH_ACTUATOR_PASSWORD=password
      - LOGSTASH_ADDRESS=logstash-service:5000
      - AMQP_URL=amqp://guest:guest@rabbitmq-service/vhost1?exchangeName=iconator_entry_exchange&exchangeType=topic&durable=true&autoDelete=false
      - BITCOIN_NETWORK=testnet
    healthcheck:
      test: ["CMD-SHELL", "curl http://iconator-kyc:8085/actuator"]
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq-service:
    restart: always
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    hostname: rabbitmq-service
    networks:
      - iconator-network
    environment:
      - RABBITMQ_DEFAULT_VHOST=vhost1

  postgres-service:
    restart: always
    image: postgres
    container_name: postgres-service
    hostname: postgres-service
    networks:
      - iconator-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser"]
      interval: 30s
      timeout: 30s
      retries: 3

  elasticsearch-service:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    container_name: elasticsearch-service
    hostname: elasticsearch-service
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - iconator-network

  kibana-service:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    container_name: kibana-service
    hostname: kibana-service
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - iconator-network
    depends_on:
      - elasticsearch-service

  logstash-service:
    image: docker.elastic.co/logstash/logstash-oss:6.2.2
    container_name: logstash-service
    hostname: logstash-service
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - iconator-network
    depends_on:
      - elasticsearch-service

networks:
  iconator-network:
